@HOST=http://localhost:5156

POST {{HOST}}/register
Content-Type: application/json

{
    "email": "Peptegrillo1rr",
    "password": "1wertewt"
}

###

POST {{HOST}}/login
Content-Type: application/json

{
    "email": "",
    "password": "1we"
}